on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: python ./.github/workflows/test.py
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Requirements Build
        id: Requirements
        uses: ryan-rozario/pipreqs-action-cpy@master
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: ./requirement.txt
  
